import AVFoundation

/// Real-time engine sound: a V8-style firing harmonic stack with combustion
/// noise and load-dependent filtering, a six-speed gearbox that drops revs on
/// each shift, turbo whistle under nitro, tyre squeal and wind. One-shot
/// effects (impacts, nitro ignition, takedowns, landings, pickups) are
/// generated by Tools/compose_sfx.py and bundled as WAV files.
@MainActor final class CarAudio {
    /// Values shared with the render thread. Plain stores of Float are
    /// tear-free on Apple silicon; the synth smooths every parameter.
    private final class Controls { var rpm: Float = 900; var load: Float = 0; var boost: Float = 0; var skid: Float = 0; var wind: Float = 0; var gain: Float = 0 }
    private let controls = Controls()
    private var engine: AVAudioEngine?
    private var effects: [String: AVAudioPlayer] = [:]
    private var gear = 1
    private var lastBoost = false
    private(set) var rpm: Double = 900
    let enabled: Bool

    static let gearTop: [Double] = [0, 15, 26, 37, 49, 62, 80] // m/s at redline per gear

    init(enabled: Bool) {
        self.enabled = enabled
        guard enabled else { return }
        for name in ["spark", "impact", "nitro", "takedown", "land", "whoosh"] {
            if let url = Bundle.main.url(forResource: name, withExtension: "wav"), let player = try? AVAudioPlayer(contentsOf: url) {
                player.prepareToPlay(); effects[name] = player
            }
        }
        effects["spark"]?.volume = 0.4
        let engine = AVAudioEngine()
        let rate = engine.outputNode.outputFormat(forBus: 0).sampleRate > 0 ? engine.outputNode.outputFormat(forBus: 0).sampleRate : 44100
        guard let format = AVAudioFormat(standardFormatWithSampleRate: rate, channels: 1) else { return }
        let source = AVAudioSourceNode(format: format, renderBlock: Self.renderer(controls: controls, sampleRate: Float(rate)))
        engine.attach(source); engine.connect(source, to: engine.mainMixerNode, format: format)
        engine.mainMixerNode.outputVolume = 0.55
        self.engine = engine
    }

    /// Builds the render closure outside the main actor so it can run on the
    /// audio thread; it only captures the shared controls and its own state.
    nonisolated private static func renderer(controls: Controls, sampleRate: Float) -> AVAudioSourceNodeRenderBlock {
        var phase: Float = 0, rpm: Float = 900, load: Float = 0, boost: Float = 0, skid: Float = 0, wind: Float = 0, gain: Float = 0
        var low: Float = 0, low2: Float = 0, windLow: Float = 0, skidBand: Float = 0, skidLow: Float = 0, whistle: Float = 0
        var noiseState: UInt32 = 22222
        let tau = Float.pi*2
        return { _, _, frameCount, bufferList in
            let buffers = UnsafeMutableAudioBufferListPointer(bufferList)
            guard let out = buffers.first?.mData?.assumingMemoryBound(to: Float.self) else { return noErr }
            let k: Float = 1/(sampleRate*0.03)
            for i in 0..<Int(frameCount) {
                rpm += (controls.rpm-rpm)*k*1.4; load += (controls.load-load)*k; boost += (controls.boost-boost)*k*0.6
                skid += (controls.skid-skid)*k*0.8; wind += (controls.wind-wind)*k*0.3; gain += (controls.gain-gain)*k*0.5
                noiseState = noiseState &* 1664525 &+ 1013904223
                let noise = Float(Int32(bitPattern: noiseState))/Float(Int32.max)
                // Four firing pulses per revolution for a V8.
                let firing = rpm/60*4
                phase += firing/sampleRate; if phase > 2 { phase -= 2 }
                let p = phase.truncatingRemainder(dividingBy: 1)
                var tone: Float = 0
                for h in 1...7 { tone += sin(tau*p*Float(h))/pow(Float(h), 0.85) }
                // Cylinder imbalance: a half-order rumble gives the burble.
                tone += 0.55*sin(tau*phase*0.5)
                let pulse = exp(-p*7)
                let combustion = noise*pulse*(0.35+load*0.6)
                var raw = tone*0.32+combustion
                // Load opens the filter: throttle sounds brighter than overrun.
                let cutoff = min(0.95, (380+load*2600+rpm*0.32)/sampleRate*tau)
                low += (raw-low)*cutoff; low2 += (low-low2)*cutoff
                raw = low2
                // Turbo whistle and intake whoosh under nitro.
                whistle += tau*(2400+rpm*0.35)/sampleRate; if whistle > tau { whistle -= tau }
                let turbo = boost*(0.05*sin(whistle)+0.06*noise)
                // Tyre squeal: resonant band of noise with a wavering pitch.
                skidBand += (noise-skidBand)*0.28; skidLow += (skidBand-skidLow)*0.12
                let squeal = (skidBand-skidLow)*skid*(0.9+0.3*sin(tau*phase*0.05))*1.8
                windLow += (noise-windLow)*0.02
                let air = windLow*wind*0.7
                let mix = (raw*(0.55+load*0.25)+turbo+squeal+air)*gain
                out[i] = tanh(mix*1.6)*0.8
            }
            for b in buffers.dropFirst() { if let data = b.mData { memcpy(data, out, Int(b.mDataByteSize)) } }
            return noErr
        }
    }

    /// Engine speed from road speed through a six-speed box; revs fall on
    /// each upshift so acceleration has audible gear changes.
    static func revs(speed: Double, gear: Int) -> Double {
        let top = gearTop[gear], bottom = gear > 1 ? gearTop[gear-1]*0.62 : 0
        return 950 + max(0, min(1.05, (speed-bottom)/(top-bottom)))*6400
    }
    func update(speed: Double, boost: Bool, drifting: Bool = false, steering: Double = 0, offRoad: Bool = false, braking: Bool = false) {
        guard let engine else { return }
        if !engine.isRunning {
            try? AVAudioSession.sharedInstance().setCategory(.ambient, mode: .default)
            try? engine.start()
        }
        if speed > Self.gearTop[gear]*0.97 && gear < 6 { gear += 1 }
        else if gear > 1 && speed < Self.gearTop[gear-1]*0.7 { gear -= 1 }
        rpm = Self.revs(speed: speed, gear: gear)
        controls.rpm = Float(rpm); controls.load = braking ? 0.05 : boost ? 1 : 0.7
        controls.boost = boost ? 1 : 0
        controls.skid = Float((drifting && abs(steering) > 0.15 && speed > 18) ? min(1, speed/40) : offRoad && speed > 15 ? 0.35 : braking && speed > 25 ? 0.4 : 0)
        controls.wind = Float(min(1, speed/75)); controls.gain = 1
        if boost && !lastBoost { play("nitro", volume: 0.55) }
        lastBoost = boost
    }
    func play(_ name: String, volume: Float = 0.7) {
        guard let p = effects[name] else { return }
        p.volume = volume; p.currentTime = 0; p.play()
    }
    func collect() { play("spark", volume: 0.45) }
    func stop() { controls.gain = 0; engine?.pause(); lastBoost = false }
}
